# Generated by Django 4.1.7 on 2023-03-24 17:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="word",
            old_name="created_date",
            new_name="created_at",
        ),
    ]
