# Generated by Django 4.1.5 on 2023-03-03 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("room_number", models.SmallIntegerField(max_length=100, unique=True)),
                ("main_player", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="word",
            name="room",
            field=models.ForeignKey(
                default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to="game.room"
            ),
        ),
    ]
