# Generated by Django 4.1.5 on 2023-03-03 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_room_word_room"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="main_player",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="room",
            name="room_number",
        ),
    ]
